## 1.  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

NumPy, short for Numerical Python, is a foundational library for scientific computing and data analysis in Python. Its primary purpose is to provide support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these data structures efficiently. Here are some key advantages and ways it enhances Python's capabilities for numerical operations:

### 1. Efficient Array Operations

    * N-dimensional Arrays: NumPy introduces the ndarray object, which allows for the creation of arrays of any dimension (1D, 2D, 3D, etc.). This flexibility is crucial for various scientific applications.
    
    * Performance: NumPy arrays are implemented in C and optimized for performance, enabling faster computations than Python's built-in lists, especially for large datasets.

### 2. Vectorization

    * Element-wise Operations: NumPy supports element-wise operations, allowing users to perform arithmetic operations on entire arrays without the need for explicit loops. This not only simplifies code but also speeds up execution.

    * Broadcasting: NumPy can automatically expand smaller arrays to match the dimensions of larger arrays, facilitating operations without requiring manual manipulation of array shapes.

### 3. Comprehensive Mathematical Functions

    * Built-in Functions: NumPy provides a wide range of mathematical functions for statistical, linear algebra, and Fourier transformations, which are essential for scientific computing.

    * Random Number Generation: The library includes functionalities for generating random numbers, useful in simulations and statistical analyses.

### 4. Interoperability

    * Integration with Other Libraries: NumPy serves as the foundation for many other scientific libraries, such as SciPy (for advanced scientific computations), Pandas (for data manipulation), and Matplotlib (for plotting). This makes it easy to build comprehensive data analysis workflows.

### 5. Memory Efficiency

    * Contiguous Memory Storage: NumPy arrays use a contiguous block of memory, leading to better cache performance and reduced memory overhead compared to lists.

    * Data Types: NumPy allows specification of data types, which can help reduce memory usage when dealing with large datasets.

### 6. Slicing and Indexing

    * Advanced Indexing: NumPy supports advanced slicing and indexing techniques, enabling efficient data manipulation and retrieval.

    * Boolean Indexing: Users can easily filter data based on conditions, making it straightforward to work with subsets of data.

### 7. Support for Mathematical Operations

    * Linear Algebra Functions: NumPy includes functions for matrix operations, including dot products, determinants, and eigenvalues, essential for solving systems of equations and other linear algebra tasks.
    
    * Fourier Transforms and Signal Processing: It provides functions for performing Fast Fourier Transforms (FFT), crucial in signal processing.

### Conclusion

In summary, NumPy significantly enhances Python's capabilities for numerical operations by providing a powerful, efficient, and user-friendly interface for array manipulation and mathematical computation. Its performance advantages, combined with its extensive functionalities and integration with other libraries, make it an essential tool for anyone working in scientific computing and data analysis. Whether you're conducting research, developing algorithms, or performing data analysis, NumPy is a key asset that simplifies complex numerical tasks.

## 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Both np.mean() and np.average() are functions in NumPy used to compute the average of array elements, but they have some differences in their functionality and use cases. Here's a comparison of the two:

### np.mean()

* Purpose: Computes the arithmetic mean (average) of the elements in an array.

* Parameters:
    * a: Input array.
    * axis: Axis along which to compute the mean. By default, it computes the mean of the flattened array.
    * dtype: Data type to use in the computation.
    * out: An optional output array to store the result.

* Usage: Best for straightforward mean calculations where all elements are treated equally.

#### Example:

In [4]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)  # Output: 3.0

### np.average()

* Purpose: Computes a weighted average of the elements in an array, but can also calculate the unweighted average if weights are not provided.

* Parameters:
    * a: Input array.
    * axis: Axis along which to compute the average. Similar to np.mean().
    * weights: Optional weights for each element. If provided, the average is calculated based on these weights.
    * returned: If True, it returns a tuple of the average and the weights used.

* Usage: Useful when you need to compute a weighted average, where different elements contribute differently to the final average.

#### Example:

In [5]:
data = np.array([1, 2, 3, 4, 5])
# Unweighted average
avg_value = np.average(data)  # Output: 3.0

# Weighted average
weights = np.array([1, 1, 1, 1, 5])
weighted_avg = np.average(data, weights=weights)  # Output: 4.0

### Key Differences

#### 1. Weights:

* np.mean() does not support weights; it treats all elements equally.

* np.average() allows for specifying weights, making it more versatile in cases where certain elements should contribute more to the average.

#### 2. Functionality:

* np.mean() is generally simpler and faster for basic mean calculations.

* np.average() provides additional functionality for weighted averages and returning weights.

#### 3. Use Cases:

* Use np.mean() when you need the arithmetic mean of an array without any special considerations for weighting.

* Use np.average() when you need a weighted average or when working with data where different observations have different levels of importance.

### Summary

In summary, choose np.mean() for straightforward average calculations and np.average() when you need to consider weights for the data points involved. Understanding the context of your data and the requirements of your analysis will guide your choice between the two functions.

## 3.  Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

Reversing a NumPy array can be done using slicing, which is a powerful feature in NumPy. You can reverse an array along different axes, depending on whether it's a 1D or a 2D array. Here’s how you can do that:

### 1D Array Reversal

For a 1D array, reversing it is straightforward. You can use slicing with a step of -1 to reverse the order of elements.

#### Example:

In [6]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Reverse the 1D array
reversed_1d = array_1d[::-1]

print("Original 1D Array:", array_1d)
print("Reversed 1D Array:", reversed_1d)


Original 1D Array: [1 2 3 4 5]
Reversed 1D Array: [5 4 3 2 1]


### 2D Array Reversal

For a 2D array, you can reverse the array along different axes (rows and columns) using similar slicing techniques.

#### Example 1: Reverse Along Rows (Vertical Reversal)
To reverse the order of rows, you can use slicing on the first axis (axis 0).

In [7]:
# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Reverse the 2D array along rows
reversed_rows = array_2d[::-1]

print("Original 2D Array:\n", array_2d)
print("Reversed 2D Array (Rows):\n", reversed_rows)


Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed 2D Array (Rows):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


#### Example 2: Reverse Along Columns (Horizontal Reversal)
To reverse the order of columns, you can use slicing on the second axis (axis 1).

In [8]:
# Reverse the 2D array along columns
reversed_columns = array_2d[:, ::-1]

print("Reversed 2D Array (Columns):\n", reversed_columns)


Reversed 2D Array (Columns):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


### Summary of Methods

* 1D Array: Use array[::-1] to reverse the entire array.

* 2D Array:
    * Reverse along rows: Use array[::-1] (to reverse the first axis).
    * Reverse along columns: Use array[:, ::-1] (to reverse the second axis).

These slicing techniques are efficient and concise, making them a powerful part of working with NumPy arrays.

## 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

In NumPy, you can determine the data type of the elements in an array using the .dtype attribute. This attribute provides information about the type of elements stored in the array, which can be crucial for memory management and performance.

### Checking Data Types
Here’s how you can check the data type of elements in a NumPy array:

#### Example:

In [10]:
import numpy as np

# Create an array with a specific data type
array_int = np.array([1, 2, 3], dtype=int)
array_float = np.array([1.0, 2.0, 3.0])
array_str = np.array(['a', 'b', 'c'])

# Check the data types
print("Data type of array_int:", array_int.dtype)      
print("Data type of array_float:", array_float.dtype)  
print("Data type of array_str:", array_str.dtype)      


Data type of array_int: int32
Data type of array_float: float64
Data type of array_str: <U1


### Importance of Data Types

#### 1. Memory Management:

* Storage Efficiency: Different data types occupy different amounts of memory. For example, an int32 uses 4 bytes, while an int64 uses 8 bytes. Choosing the appropriate data type helps optimize memory usage, especially when dealing with large datasets.

* Array Size: When creating large arrays, using a smaller data type (e.g., float32 instead of float64 or int8 instead of int64) can significantly reduce memory consumption, allowing you to work with larger datasets without running into memory limitations.

#### 2. Performance:

* Computation Speed: Operations on smaller data types can be faster because they require less memory bandwidth and can improve cache performance. For instance, arithmetic operations on float32 are generally faster than on float64 due to the reduced amount of data being processed.

* Vectorization: NumPy is optimized for array operations. If the data types are appropriate, it can leverage SIMD (Single Instruction, Multiple Data) instructions on CPUs to perform operations more efficiently.

#### 3. Type-Safety:

* Avoiding Errors: Specifying the correct data type helps in preventing errors. For instance, if you attempt to perform operations between incompatible types, NumPy will raise errors, helping to identify potential issues in the code.

* Explicit Control: By specifying data types, you can ensure that your calculations behave as expected. This is particularly important in scientific computing, where precision matters.

#### 4. Interoperability:

* When working with other libraries (like Pandas, SciPy, or machine learning frameworks), ensuring that your NumPy arrays have the correct data type can be crucial for compatibility and performance.

### Conclusion

Understanding and managing data types in NumPy is vital for optimizing both memory usage and computational efficiency. By using the appropriate data types, you can enhance the performance of your applications and handle larger datasets more effectively. Always check the data type of your arrays with .dtype and choose types that align with your specific use case to achieve the best results.

## 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In NumPy, ndarrays (N-dimensional arrays) are the core data structure designed for efficient numerical computations. They are a powerful alternative to standard Python lists, offering several key features and advantages that make them ideal for scientific computing and data analysis.

### Key Features of ndarrays

#### 1. Homogeneous Data Types:

* All elements in an ndarray must be of the same data type. This uniformity allows for optimized storage and performance, as operations can be executed more efficiently compared to heterogeneous data types.

#### 2. Multi-dimensional:

* ndarrays can have multiple dimensions (1D, 2D, 3D, etc.), allowing for the representation of complex datasets. For example, a 2D array can represent a matrix, while a 3D array can represent a collection of matrices (like an image stack).

#### 3. Fixed Size:

* Once created, the size of an ndarray cannot be changed. This characteristic makes them more efficient than Python lists, which can dynamically resize. However, you can create a new ndarray if you need a different size.

#### 4. Contiguous Memory Allocation:

* ndarrays are stored in contiguous blocks of memory, which enhances performance by optimizing cache usage. This is in contrast to Python lists, which are arrays of pointers to objects, leading to potential overhead.

#### 5. Vectorized Operations:

* NumPy allows for element-wise operations on entire arrays without the need for explicit loops. This vectorization results in concise code and significantly faster execution times, leveraging underlying C and Fortran libraries.

#### 6. Broadcasting:

* NumPy supports broadcasting, which allows for arithmetic operations on arrays of different shapes. This flexibility enables efficient computations without needing to manually align shapes.

#### 7. Comprehensive Mathematical Functions:

* NumPy provides a wide range of built-in mathematical functions for statistical operations, linear algebra, Fourier transforms, and more, all optimized for ndarrays.

#### 8. Slicing and Indexing:

* ndarrays support advanced slicing and indexing capabilities, allowing for sophisticated data manipulation and retrieval. This feature is more powerful than the basic slicing available with Python lists.

### Differences from Standard Python Lists

#### 1. Data Type Uniformity:

* ndarrays: Homogeneous (same type for all elements).
* Python Lists: Heterogeneous (can contain mixed types).

#### 2. Performance:

* ndarrays: Faster for numerical computations due to optimized memory usage and vectorization.
* Python Lists: Slower for numerical operations, especially with large datasets due to the overhead of managing pointers.

#### 3. Dimensionality:

* ndarrays: Can be multi-dimensional (N-dimensional).
* Python Lists: Primarily 1D but can contain nested lists to create multi-dimensional structures, though this is less efficient and more cumbersome.

#### 4. Memory Consumption:

* ndarrays: Use less memory per element, particularly for numerical types.
* Python Lists: Have a larger memory overhead due to storing pointers to objects.

#### 5. Functionality:

* ndarrays: Come with a rich set of mathematical operations and functions.
* Python Lists: Basic functionalities; advanced mathematical operations require additional code or libraries.

## 6.  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays offer several performance benefits over Python lists, particularly for large-scale numerical operations. Here are the key advantages:

### 1. Memory Efficiency

* Contiguous Memory Allocation: NumPy arrays store data in contiguous memory blocks, which reduces overhead and leads to better cache utilization. In contrast, Python lists are arrays of pointers to objects, which can result in increased memory consumption and fragmentation.
* Fixed Data Types: NumPy arrays require elements to be of the same type, allowing for more compact storage. Python lists, being heterogeneous, can use more memory for type information.

### 2. Performance Speed

* Vectorized Operations: NumPy supports vectorized operations, allowing element-wise operations on arrays without the need for explicit loops in Python. This leads to significant speedups, especially for large datasets, as operations are implemented in optimized C code.
* Broadcasting: NumPy can automatically expand arrays of different shapes for operations, which avoids the need for manual replication of data, enhancing both performance and code simplicity.

### 3. Optimized Libraries

* BLAS and LAPACK: NumPy leverages highly optimized linear algebra libraries (like BLAS and LAPACK) for mathematical computations. These libraries are implemented in low-level languages and are highly optimized for performance.
* Compiled Functions: Many NumPy functions are implemented in C, which can provide speed advantages over Python functions that are interpreted.

### 4. Reduced Overhead

* Less Overhead for Operations: Operations on NumPy arrays have lower overhead compared to Python lists, due to the reduction in type checks and method calls. This is especially noticeable in loops and bulk operations.

### 5. Advanced Indexing and Slicing

* Efficient Slicing: NumPy's slicing is more efficient because it returns views of the array instead of copies. This allows for modifications without duplicating data.
* Fancy Indexing: NumPy allows for advanced indexing techniques that can lead to concise and faster code for extracting and manipulating subsets of data.

### 6. Parallelism

* Multithreading: Many NumPy operations can be parallelized at a low level, taking advantage of multicore processors, which is often not possible with Python lists without additional libraries.

### 7. Functionality

* Rich Functionality: NumPy provides a wide range of mathematical functions, linear algebra routines, and statistical operations that are optimized for performance, facilitating complex numerical tasks without the need for external libraries.

### Conclusion

For large-scale numerical operations, NumPy arrays significantly outperform Python lists in terms of speed, memory efficiency, and functionality. This makes them the preferred choice for scientific computing, data analysis, and any application involving substantial numerical data processing.

## 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

In NumPy, vstack() and hstack() are functions used to stack arrays vertically and horizontally, respectively. They are particularly useful for combining arrays of compatible shapes.

### 1. vstack()

vstack() stacks arrays vertically (row-wise). The input arrays must have the same shape along all but the first axis.

#### Example of vstack()

In [2]:
import numpy as np

# Creating two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stacking vertically
result_vstack = np.vstack((array1, array2))

print("Result of vstack:")
print(result_vstack)

Result of vstack:
[[1 2 3]
 [4 5 6]]


### 2. hstack()

hstack() stacks arrays horizontally (column-wise). The input arrays must have the same number of dimensions along all but the second axis.

#### Example of hstack()

In [3]:
# Creating two 2D arrays
array3 = np.array([[1, 2, 3], [7, 8, 9]])
array4 = np.array([[4, 5, 6], [10, 11, 12]])

# Stacking horizontally
result_hstack = np.hstack((array3, array4))

print("Result of hstack:")
print(result_hstack)


Result of hstack:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### Summary

* vstack(): Stacks arrays vertically, increasing the number of rows.
* hstack(): Stacks arrays horizontally, increasing the number of columns.

Both functions are handy for combining data in different ways, depending on how we want to structure your arrays.

## 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

In NumPy, the functions fliplr() and flipud() are used to flip arrays, but they operate in different orientations. Here’s a detailed explanation of each, along with their effects on different array dimensions.

### 1. fliplr()

* Function: fliplr() flips an array from left to right (i.e., it reverses the order of the columns).
* Usage: It operates on 2D arrays and can also be applied to higher-dimensional arrays, where it flips the last dimension (the columns).

#### Example of fliplr()

In [4]:
import numpy as np

array2D = np.array([[1, 2, 3],
                    [4, 5, 6]])

result_fliplr = np.fliplr(array2D)

print("Original Array:")
print(array2D)
print("\nArray after fliplr:")
print(result_fliplr)


Original Array:
[[1 2 3]
 [4 5 6]]

Array after fliplr:
[[3 2 1]
 [6 5 4]]


### 2. flipud()

* Function: flipud() flips an array upside down (i.e., it reverses the order of the rows).
* Usage: It operates on 2D arrays and higher-dimensional arrays, where it flips the first dimension (the rows).

#### Example of flipud()

In [5]:
result_flipud = np.flipud(array2D)

print("\nArray after flipud:")
print(result_flipud)



Array after flipud:
[[4 5 6]
 [1 2 3]]


### Effects on Different Array Dimensions

#### 2D Arrays:

* fliplr(): Flips columns.
* flipud(): Flips rows.

#### 1D Arrays:

* Both functions will behave the same since there are no columns or rows to flip. The output will be the same for both methods.

#### Example with 1D Array

In [6]:
array1D = np.array([1, 2, 3, 4, 5])

result_fliplr_1d = np.fliplr(array1D.reshape(1, -1))  # Reshape for fliplr
result_flipud_1d = np.flipud(array1D)

print("\n1D Array flipped with fliplr (as 2D):")
print(result_fliplr_1d)
print("\n1D Array flipped with flipud:")
print(result_flipud_1d)



1D Array flipped with fliplr (as 2D):
[[5 4 3 2 1]]

1D Array flipped with flipud:
[5 4 3 2 1]


### Summary

* fliplr(): Flips the array left to right (column-wise) for 2D arrays.
* flipud(): Flips the array upside down (row-wise) for 2D arrays.
* For 1D arrays, both will effectively reverse the order of elements.

These functions are useful for manipulating the orientation of data in an array, particularly in image processing or data analysis tasks.

## 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The array_split() method in NumPy is used to divide an array into multiple sub-arrays along a specified axis. It provides flexibility when splitting arrays, especially when the total number of elements does not evenly divide by the number of desired splits.

### Functionality of array_split()

Syntax:

* ary: The input array to be split.

* indices_or_sections: This can be an integer (number of splits) or a list of indices where the splits should occur.

* axis: The axis along which to split the array (default is 0).

#### Key Features:

1. Splitting by Number of Sections: If you specify an integer, NumPy will attempt to split the array into that many equal sections. If the array cannot be split evenly, NumPy will create sub-arrays of varying sizes.

2. Splitting by Indices: You can also provide a list of indices. This tells NumPy where to make the splits. The resulting sub-arrays will have sizes based on the indices specified.

3. Supports Multi-dimensional Arrays: The function can be used on arrays of any dimension, and the splitting occurs along the specified axis.

### Handling Uneven Splits

When the total number of elements in the array does not evenly divide by the number of requested splits, array_split() ensures that:

* The first few sub-arrays will have one more element than the remaining sub-arrays.
* The function maintains the order of the elements and redistributes them as evenly as possible.

### Examples

#### Example 1: Splitting by Number of Sections

In [9]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Split into 3 sections
split_array = np.array_split(array, 3)

print("Array Split into 3 sections:")
for i, arr in enumerate(split_array):
    print(f"Section {i + 1}: {arr}")


Array Split into 3 sections:
Section 1: [1 2 3]
Section 2: [4 5 6]
Section 3: [7 8]


#### Example 2: Splitting by Indices

In [10]:
# Split at indices 2 and 5
split_array_indices = np.array_split(array, [2, 5])

print("\nArray Split at indices 2 and 5:")
for i, arr in enumerate(split_array_indices):
    print(f"Section {i + 1}: {arr}")



Array Split at indices 2 and 5:
Section 1: [1 2]
Section 2: [3 4 5]
Section 3: [6 7 8]


#### Example 3: 2D Array Split

In [11]:
array_2D = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Split into 2 sections along the first axis
split_array_2D = np.array_split(array_2D, 2, axis=0)

print("\n2D Array Split into 2 sections:")
for i, arr in enumerate(split_array_2D):
    print(f"Section {i + 1}:\n{arr}")



2D Array Split into 2 sections:
Section 1:
[[1 2 3]
 [4 5 6]]
Section 2:
[[7 8 9]]


### Summary

* array_split() allows for flexible splitting of arrays into sub-arrays.
* It handles uneven splits gracefully, ensuring that the elements are distributed as evenly as possible.
* The function works for both 1D and multi-dimensional arrays, making it versatile for various applications in data manipulation and analysis.

## 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Vectorization and broadcasting are two fundamental concepts in NumPy that enhance the efficiency and performance of array operations, especially in numerical computing.

### Vectorization

Concept: Vectorization refers to the process of applying operations to entire arrays (or large sections of arrays) without the need for explicit loops in Python. Instead of iterating over individual elements, vectorized operations leverage optimized C and Fortran code underneath, leading to faster execution.

##### Benefits:

1. Performance: Vectorized operations are typically much faster than their loop-based counterparts. This is because the underlying implementations are optimized and can take advantage of low-level optimizations and CPU capabilities.
2. Concise Code: Vectorization leads to cleaner and more readable code. It allows for expressing operations in a more mathematical way, which is often more intuitive.

#### Example: Instead of using a loop to add two arrays element-wise:

In [12]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Using a loop
result = np.zeros(3)
for i in range(len(a)):
    result[i] = a[i] + b[i]

# Vectorized approach
result_vectorized = a + b


The vectorized operation a + b is not only more efficient but also more concise.

### Broadcasting

Concept: Broadcasting is a technique that allows NumPy to perform arithmetic operations on arrays of different shapes. When performing operations on arrays, NumPy automatically expands the smaller array across the larger array so that they have compatible shapes.

#### How It Works:

* Alignment: NumPy compares the shapes of the arrays involved in the operation. If they do not match, it attempts to align them by expanding the dimensions of the smaller array.
* Rules for Broadcasting:
    1. If the arrays have different numbers of dimensions, the shape of the smaller array is padded with ones on the left side until both shapes are the same.
    2. The sizes of the dimensions are compared:
        * If they are equal, they are compatible.
        * If one of the dimensions is 1, that dimension is expanded to match the other.
        * If the sizes are different and neither is 1, broadcasting fails.

#### Example: Consider adding a 1D array to a 2D array:

In [14]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

# Broadcasting
result_broadcasting = a + b

### Contribution to Efficient Array Operations

1. Reduced Overhead: By eliminating the need for explicit loops, vectorization reduces the overhead associated with Python function calls and context switching.

2. Optimized Execution: Both vectorization and broadcasting leverage highly optimized libraries (like BLAS and LAPACK) that can execute operations in compiled languages, resulting in significant speed improvements.

3. Memory Efficiency: Broadcasting allows for the use of smaller arrays without needing to create large temporary copies, conserving memory.

4. Simplicity and Readability: Vectorized and broadcasted operations lead to clearer and more maintainable code, making it easier to express complex mathematical operations succinctly.

### Conclusion

Together, vectorization and broadcasting enable efficient array operations in NumPy, significantly enhancing performance while simplifying code. These features make NumPy a powerful tool for numerical computations, data analysis, and scientific computing.

# Practical Questions:

## 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

To create a 3x3 NumPy array with random integers between 1 and 100 and then interchange its rows and columns (i.e., perform a transpose operation), we can use the following code:

In [15]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

print("Original Array:")
print(array)

# Interchange rows and columns (transpose)
transposed_array = array.T

print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[55 36 29]
 [45 79 74]
 [43  9 65]]

Transposed Array:
[[55 45 43]
 [36 79  9]
 [29 74 65]]


### Explanation:

1. Creating the Array: The np.random.randint(1, 101, size=(3, 3)) function generates a 3x3 array with random integers ranging from 1 to 100.
2. Transposing the Array: The .T attribute is used to transpose the array, effectively interchanging its rows and columns.

 The actual numbers will vary each time we run the code due to the random generation.

## 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

We can generate a 1D NumPy array with 10 elements and reshape it into a 2x5 array and then into a 5x2 array using the following code:

In [16]:
import numpy as np

# Generate a 1D array with 10 elements
array_1d = np.arange(10)  # This will create an array with elements [0, 1, 2, ..., 9]

print("Original 1D Array:")
print(array_1d)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:")
print(array_2x5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped to 5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### Explanation:

1. Generating the 1D Array: The np.arange(10) function creates a 1D array containing the integers from 0 to 9.
2. Reshaping:
    * The reshape(2, 5) method transforms the 1D array into a 2x5 array.
    * The reshape(5, 2) method transforms the 1D array into a 5x2 array.

This output demonstrates the original array and the reshaped forms.

## 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

We can create a 4x4 NumPy array with random float values and then add a border of zeros around it to create a 6x6 array using the following code:

In [17]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)  # Generates values between 0 and 1

print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("\n6x6 Array with Border of Zeros:")
print(array_with_border)


Original 4x4 Array:
[[0.01834169 0.69713604 0.23113671 0.13384415]
 [0.33590463 0.69512602 0.92024653 0.32586875]
 [0.18360352 0.14799664 0.88691774 0.32714608]
 [0.68082324 0.805809   0.51255524 0.10056577]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.01834169 0.69713604 0.23113671 0.13384415 0.        ]
 [0.         0.33590463 0.69512602 0.92024653 0.32586875 0.        ]
 [0.         0.18360352 0.14799664 0.88691774 0.32714608 0.        ]
 [0.         0.68082324 0.805809   0.51255524 0.10056577 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


### Explanation:

1. Generating the 4x4 Array: The np.random.rand(4, 4) function generates a 4x4 array with random float values between 0 and 1.
2. Adding the Border: The np.pad() function adds a border of zeros around the original array. The pad_width=1 argument specifies that one layer of zeros should be added around all sides, and mode='constant' with constant_values=0 indicates that the padding value should be zero.

The actual random values will differ each time you run the code, but the structure of the arrays will remain consistent.

## 4.  Using NumPy, create an array of integers from 10 to 60 with a step of 5.

We can create an array of integers from 10 to 60 with a step of 5 using the np.arange() function in NumPy. Here’s how to do it:

In [18]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


### Explanation:
np.arange(start, stop, step): This function generates values starting from start, up to (but not including) stop, with the specified step.

This creates an array that includes all integers from 10 to 60, incrementing by 5.

## 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

We can create a NumPy array of strings and then apply different case transformations to each element using NumPy's vectorized string operations. Here's how to do it:

In [19]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
capitalize_array = np.char.capitalize(array)

# Print the results
print("Original Array:")
print(array)

print("\nUppercase:")
print(uppercase_array)

print("\nLowercase:")
print(lowercase_array)

print("\nTitle Case:")
print(titlecase_array)

print("\nCapitalized:")
print(capitalize_array)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalized:
['Python' 'Numpy' 'Pandas']


### Explanation:

1. Creating the Array: The array is created with three string elements.
2. String Operations:
    * np.char.upper(): Converts each string to uppercase.
    * np.char.lower(): Converts each string to lowercase.
    * np.char.title(): Converts each string to title case (first letter of each word capitalized).
    * np.char.capitalize(): Capitalizes the first letter of each string.

This shows the original array alongside the transformed versions, demonstrating the various case transformations applied to each string element.

## 6.  Generate a NumPy array of words. Insert a space between each character of every word in the array.

We can generate a NumPy array of words and insert a space between each character of every word using NumPy's string operations. Here's how to do it:

In [20]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_array = np.char.join(' ', words_array)

# Print the results
print("Original Array:")
print(words_array)

print("\nArray with spaces between characters:")
print(spaced_array)


Original Array:
['hello' 'world' 'numpy' 'python']

Array with spaces between characters:
['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


### Explanation:

1. Creating the Array: The array is created with four words.
2. Inserting Spaces: The np.char.join() function is used to insert a space between each character in the words. The first argument is the string to insert (in this case, a single space), and the second argument is the array of words.

This shows the original array of words alongside the modified array where spaces have been inserted between the characters of each word.

## 7.  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

We can create two 2D NumPy arrays and perform element-wise operations such as addition, subtraction, multiplication, and division using the following code:

In [21]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise addition
addition_result = array1 + array2

# Perform element-wise subtraction
subtraction_result = array1 - array2

# Perform element-wise multiplication
multiplication_result = array1 * array2

# Perform element-wise division
division_result = array1 / array2

# Print the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition_result)

print("\nElement-wise Subtraction:")
print(subtraction_result)

print("\nElement-wise Multiplication:")
print(multiplication_result)

print("\nElement-wise Division:")
print(division_result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


### Explanation:

1. Creating the Arrays: Two 2D arrays, array1 and array2, are created with different integer values.

2. Element-wise Operations:
    
    * Addition: array1 + array2
   
    * Subtraction: array1 - array2
    
    * Multiplication: array1 * array2
    
    * Division: array1 / array2

This output shows the original arrays alongside the results of the element-wise addition, subtraction, multiplication, and division operations.

## 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

We can create a 5x5 identity matrix using NumPy and then extract its diagonal elements with the following code:

In [22]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


### Explanation:

1. Creating the Identity Matrix: The np.eye(5) function generates a 5x5 identity matrix, where all the elements on the main diagonal are 1, and all other elements are 0.

2. Extracting the Diagonal: The np.diag() function is used to extract the diagonal elements from the identity matrix.

## 9.  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

We can generate a NumPy array of 100 random integers between 0 and 1000 and then find and display all prime numbers in that array using the following code:

In [23]:
import numpy as np

# Generate an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = np.array([num for num in random_integers if is_prime(num)])

# Print the results
print("Random Integers Array:")
print(random_integers)

print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Integers Array:
[653 142 606 460 210 228 125 275 155 179 373 122 298 644  49 482 590 654
 755 531 268  16 786 388 118 573 187 688  45 510 864  49 106 514 271 796
 980 206  48 773 799 996 183 378 891 790 942 748 469 876 997 171 318 950
  42 252 913 502 407 450  51 674 970 107 459 333 886 526 692 687  20 999
   2 591 349 940 105 645 931 884 419 403 114 933 556  86 271 757 602 378
 771 204 109 538 912 689  99 564 635 535]

Prime Numbers in the Array:
[653 179 373 271 773 997 107   2 349 419 271 757 109]


### Explanation:

1. Generating Random Integers: The np.random.randint(0, 1001, size=100) function generates an array of 100 random integers between 0 and 1000.

2. Prime Checking Function: The is_prime function checks if a number is prime:
    * It returns False for numbers less than or equal to 1.
    * It checks divisibility from 2 up to the square root of the number.

3. Finding Prime Numbers: A list comprehension is used to filter out prime numbers from the random integers array.

4. Results: The original array and the prime numbers found in it are printed.

In this output, the random integers array contains various numbers, and the prime numbers extracted from it are displayed. The actual numbers will change with each execution due to randomness.

## 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

We can create a NumPy array representing daily temperatures for a month (30 days) and then calculate and display the weekly averages using the following code:

In [38]:
import numpy as np

# Generate a NumPy array representing daily temperatures for 30 days
# Let's assume temperatures are between 15 and 30 degrees Celsius
daily_temperatures = np.random.uniform(15, 30, size=30)

print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Reshape the array into weeks (4 weeks of 7 days each + 2 extra days)
# Note: For simplicity, we can consider the last week with the available days.
weeks = daily_temperatures.reshape(4, 7)

# Calculate weekly averages
weekly_averages = np.mean(weeks, axis=1)

print("\nWeekly Averages:")
print(weekly_averages)

Daily Temperatures for the Month:
[16.17763508 23.3339284  15.12591031 28.28205007 28.12010461 20.40363989
 29.06261887 17.53738346 20.83801748 18.7740609  20.1947613  18.48714395
 20.68377389 18.79884224 23.92615638 25.73734809 19.89930121 17.30423311
 28.78353761 17.65572463 20.57067105 26.53319648 24.42727822 22.10559903
 20.12178319 23.13337304 29.38157695 24.63551564 19.8624791  21.46215941]


<class 'ValueError'>: cannot reshape array of size 30 into shape (4,7)

### Explanation:

1. Generating Daily Temperatures: The np.random.uniform(15, 30, size=30) function generates an array of 30 random float values between 15 and 30 degrees Celsius to represent daily temperatures.
2. Reshaping for Weeks: The array is reshaped into a 4x7 array, representing 4 complete weeks. The last week will contain the remaining days (if needed).
3. Calculating Weekly Averages: The np.mean() function calculates the average temperature for each week along the specified axis (1 for rows).

This output shows the daily temperatures for a month and the calculated weekly averages, demonstrating how to manage and analyze temperature data using NumPy.